pars <- list(x = rbind(c(0.8, 0.2), #first row is group 1's mixing group 1,2,3,4,5
                       c(0.2, 0.8)),
             alpha = 1.25,
             UN_1_ini = c(41042,37884), #number initially uninvolved, no police contact
             UN_2_ini = c(17679,16319), #number initially uninvolved, no police contact - 93.6% of the excluded
             UN_3_ini = c(0,0), #number initially uninvolved, no police contact - zero for close, all already flagged
             US_1_ini = c(0,0), #number initially uninvolved, surveilled - zero for included
             US_2_ini = c(1263,1165), #number initially uninvolved, surveilled - 6.6% of the excluded
             US_3_ini = c(4249,1821), #number initially uninvolved, surveilled - 100% of the close
             UR_1_ini = c(4,2), #number initially uninvolved, in CSJ - lets say 800 start in the CSJ (i just picked), and i split between 3
             UR_2_ini = c(356,39), #number initially uninvolved, in CSJ
             UR_3_ini = c(360,40), #number initially uninvolved, in CSJ
             WN_1_ini = c(0,0), #number initially working, no police contact
             WN_2_ini = c(0,0), #number initially working, no police contact
             WN_3_ini = c(0,0), #number initially working, no police contact
             WS_1_ini = c(0,0), #number initially working, surveilled
             WS_2_ini = c(1,0), #number initially working, surveilled
             WS_3_ini = c(5,1), #number initially working, surveilled -lets start small working & hope it takes off?
             WR_1_ini = c(0,0), #number initially working, in CSJ
             WR_2_ini = c(1,0), #number initially working, in CSJ
             WR_3_ini = c(1,0), #number initially working, in CSJ
             J_1_ini = c(1,0), #number initially on custodial sentence
             J_2_ini = c(7,0), #number initially on custodial sentence
             J_3_ini = c(25,5), #number initially on custodial sentence - prev of custodial sentence is 38 so, just split it
             JW_1_ini = c(0,0), #number of CL initially on custodial sentence
             JW_2_ini = c(0,0), #number of CL initially on custodial sentence
             JW_3_ini = c(1,0), #number of CL initially on custodial sentence
             JR_1_ini = c(0,0), #number initially remanded to custody - none
             JR_2_ini = c(4,0), #number initially remanded to custody - prevalence of remand is 9.5 so just split between these
             JR_3_ini = c(3,1.5), #number initially remanded to custody - prevalence of remand is 9.5 so just split between these
             JRW_1_ini = c(0,0), #number of CL initially remanded to custody
             JRW_2_ini = c(0,0), #number of CL initially remanded to custody -
             JRW_3_ini = c(0,0), #number of CL initially remanded to custody -
             age_in = c(0,0), #boys, girls  coming in weekly - should be set to [151, 141]
             excl_in = c(0.29,0.19), #percent boys, girls  coming in going to excluded
             close_in = c(0.01,0.01), #percent boys, girls  coming in going to close
             surv_in_i = c(0,0), #pc of boys, girls  in INCLUDED that are surveilled at 10
             surv_in_e = c(0.07,0.07), #pc of gboys, girls  in EXCLUDED that are surveilled at 10
             surv_in_c = c(0.6,0.5), #pc of boys, girls in CLOSE that are surveilled at 10
             missing_i = c(0,0), #rate of missing episodes for the included group
             missing_e = c(0.003,0.003), #rate of missing episodes for the excluded group
             missing_c = c(0.03,0.03), #rate of missing episodes for the close group
             ss_i = c(0.00003529546,0.000002799211), #rate of stop&search for the included group
             ss_e = c(0.001087095,0.00009400705), #rate of stop&search  for the excluded group
             ss_c = c(0.003954082,0.0009812287), #rate of stop&search  for the close group
             recruit_1 = c(0.0005,0.0001),
             recruit_2 = c(0.001,0.0009),
             recruit_3 = c(0.005,0.003),
             recruit_j = c(0.005,0.003),
             custody_fte = c(0.015,0.003), #percentage of fte's that get a custodial sentence (of men, 1.5% - of women, 0.3%)
             custody_rep = c(0.14,0.04), #percentage of repeat offenders that get a custodial sentence (that weren't remanded to custody)
             fte1 = c(0.00001088204,0.000003463907), #some kind of rate of included first time entrants
             fte2 = c(0.0003351652,0.0001170569), #some kind of rate of excluded first time entrants
             fte3 = c(0.001219093,0.001214229), #some kind of rate of close first time entrants total (should work out as like 600 a year, 23% female 77% male)
             rep = c(0.002,0.001), #some kind of rate of repeated offences (should work out as like 452
             school_ex_i = c(0.0009615385,0.0004807692), #rc(0,0),#ates of school exclusion, included
             school_ex_e = c(0.005769231,0.001923077), #c(0,0),
             impov = 0.003, # 0.0003205128 pretty steep impoverishment rate of like 1 pc of pop a year or something like that?
             u1_out = c(0,0),  #percentage of exiters leaving from this state, boy and girl
             us1_out = c(0,0),
             ur1_out = c(0,0),
             w1_out = c(0,0),
             ws1_out = c(0,0),
             wr1_out = c(0,0),
             j1_out = c(0,0),
             jr1_out = c(0,0),
             jw1_out = c(0,0),
             jrw1_out = c(0,0),
             u2_out = c(0,0),
             us2_out = c(0,0),
             ur2_out = c(0,0),
             w2_out = c(0,0),
             ws2_out = c(0,0),
             wr2_out = c(0,0),
             j2_out = c(0,0),
             jr2_out = c(0,0),
             jw2_out = c(0,0),
             jrw2_out = c(0,0),
             u3_out = c(0,0),
             us3_out = c(0,0),
             ur3_out = c(0,0),
             w3_out = c(0,0),
             ws3_out = c(0,0),
             wr3_out = c(0,0),
             j3_out = c(0,0),
             jr3_out = c(0,0),
             jw3_out = c(0,0),
             jrw3_out = c(0,0)
)
